# Generated by Django 5.2.13 on 2026-04-13 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_tournament_match'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchPlayerCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(choices=[('yellow', 'Yellow'), ('red', 'Red')], max_length=10)),
                ('minute', models.IntegerField()),
                ('comments', models.TextField(blank=True, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='api.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='api.player')),
            ],
        ),
        migrations.CreateModel(
            name='MatchPlayerGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('own_goal', models.BooleanField(default=False)),
                ('minute', models.IntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='api.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='api.player')),
            ],
        ),
    ]
