# Generated by Django 5.2.13 on 2026-04-13 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_matchplayercard_matchplayergoal'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchplayercard',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_player_cards', to='api.team'),
        ),
        migrations.AddField(
            model_name='matchplayergoal',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_player_goals', to='api.team'),
        ),
    ]
