# Generated by Django 5.2.13 on 2026-05-17 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_match_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='teams/'),
        ),
    ]
