# Generated by Django 5.2.13 on 2026-05-17 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_appuser_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='users/'),
        ),
    ]
